export const caseStudiesEn: Record<string, {title:string;sections:{title:string;text:string}[]}> = {
 "pinacoteca-di-brera":{title:"A new digital presence for the museum.",sections:[{title:"From entering the museum to discovering its artworks",text:"The website brings together three moments of navigation: entering the museum, exploring its masterpieces and looking closely at an individual artwork. A journey connecting the collection as a whole with the details of each work."},{title:"An ongoing collaboration",text:"The project continues a collaboration that includes the museum’s previous website, with content about collections, activities and restoration, high-resolution images and video."},{title:"Bottega Brera",text:"For the Pinacoteca’s design and bookstore, we created the name Bottega Brera, designed its logo and developed the space’s visual design. The museum’s story enters the physical space through identity, images and words."}]},
 "palazzo-citterio":{title:"From the website to the museum spaces.",sections:[{title:"Finding your way through the museum",text:"Our work continued with museum graphics and wayfinding, helping visitors understand the exhibition route. The website and the physical spaces offer two distinct ways to connect the museum with its audience."}]},
 "cenacolo-vinciano":{title:"A story that continues online.",sections:[{title:"Giving the museum a voice",text:"We created the website’s teaser video. Our subsequent work on social channels, in collaboration with the museum, uses content to tell the story of its heritage and invite the public to discover it."}]},
 "biblioteca-braidense":{title:"Discovering collections and activities online.",sections:[{title:"The programme at a glance",text:"We created an events calendar for browsing upcoming activities and planning a visit. The life of the library has a dedicated space alongside the story of its collections."}]},
 "poldi-pezzoli":{title:"The museum, from digital design to visitor materials.",sections:[{title:"A new website for the museum",text:"The new museum website complements the visitor map and brochure, opening another way to explore the collections."},{title:"Piero della Francesca: an exhibition identity",text:"For the exhibition reuniting the Augustinian polyptych, we created the visual identity, design and teaser video. A distinct project expressed through its own materials and visual language."}]},
 "palazzo-boncompagni":{title:"Identity and communication for exhibitions.",sections:[{title:"Aldo Mondino. Impertinenze a Palazzo",text:"Our work accompanied the Aldo Mondino exhibition, from its identity and publications to campaigns and social content."},{title:"Mimmo Paladino nel Palazzo del Papa",text:"For the Mimmo Paladino exhibition, we developed the logo, visual, catalogue, advertising and social content. Together, these exhibitions show how a project takes shape across different media."}]},
 "galleria-cavour":{title:"Identity, art and communication.",sections:[{title:"Art on the façade",text:"We also created digital communication and video for Pietro Terzini’s intervention on the gallery’s façade. A story about the artwork and its encounter with the urban space."}]},
 "explora":{title:"A website to discover, play and learn.",sections:[{title:"Telling the possibilities of discovery",text:"Exhibits, activities and workshops are at the heart of the museum’s story. The website presents this world of experiences and provides an introduction to its educational programme."}]},
};
