import type { Project } from "./projects";
import { projects } from "./projects";

const translations: Record<string, Pick<Project, "alt" | "discipline" | "description">> = {
  "pinacoteca-di-brera": { alt: "Brera website mockup showing the homepage, collections and an artwork page", discipline: "Web design, development, communication", description: "In 2024, we designed and developed the new Pinacoteca di Brera website. A new chapter in a collaboration that has brought together digital experiences, content and visual communication over time." },
  "palazzo-citterio": { alt: "Palazzo Citterio galleries with museum graphics beside the artworks", discipline: "Web design, museum graphics, wayfinding", description: "From the new website and communication materials to museum graphics and wayfinding, our work for Palazzo Citterio addresses the encounter with the museum both online and along the exhibition route." },
  "cenacolo-vinciano": { alt: "The Cenacolo Vinciano museum website on desktop, tablet and phone", discipline: "Web design, storytelling, video", description: "We designed and developed the Museo del Cenacolo Vinciano website, bringing together visitor information, storytelling and high-resolution images. The project includes a teaser video; subsequent social media work extends the museum’s story." },
  "biblioteca-braidense": { alt: "Braidense Library website pages displayed on different devices", discipline: "Web design, content, events calendar", description: "Collections and activities in a structure designed for clear navigation. For the Biblioteca Nazionale Braidense, we worked on the new website and a calendar to explore the programme and plan a visit." },
  "poldi-pezzoli": { alt: "Poldi Pezzoli website presentation featuring a painting detail and red drapery", discipline: "Web, visitor materials, visual identity", description: "A new map and brochure to guide visitors, a new website and communication for the exhibition reuniting Piero della Francesca’s Augustinian polyptych. Distinct projects spanning digital design, graphics and the museum’s stories." },
  "palazzo-boncompagni": { alt: "Blue and gold exhibition visual for Mimmo Paladino at Palazzo Boncompagni", discipline: "Identity, publications, campaigns", description: "For the Aldo Mondino and Mimmo Paladino exhibitions at Palazzo Boncompagni, we created logos and visuals, catalogues, advertising and social media content. Two projects combining visual communication, publishing and cultural promotion." },
  "galleria-cavour": { alt: "Yellow and black This is the Place poster for Galleria Cavour 1959", discipline: "Visual identity, advertising, video", description: "Visual identity, design and digital advertising for Galleria Cavour 1959. Our work also includes digital communication and video dedicated to artist Pietro Terzini’s intervention on the gallery’s façade." },
  "explora": { alt: "Explora children’s museum in Rome", discipline: "Planning, web design, development", description: "For Explora, the children’s museum in Rome, we planned, designed and developed the new website. A project dedicated to a place where play and learning meet, for children and the adults accompanying them." },
};

export const englishProjects: readonly Project[] = projects.map((project) => ({ ...project, ...translations[project.slug] }));
