from pathlib import Path
import json
R=Path(__file__).resolve().parents[1];D=R/'discovery';U=R/'backup/public/old/wp-content/uploads'
P={p['id']:p for p in json.loads((D/'contents.json').read_text())};M={m['id']:m for m in json.loads((D/'media.json').read_text())}
cases=[
('palazzo-citterio','Palazzo Citterio','Dal sito agli spazi del museo','2024–2025','Design e sviluppo web · Materiali di comunicazione · Grafica museale e wayfinding',['2508','2529'],[
('Una nuova apertura, anche online','In occasione dell’apertura di Palazzo Citterio nel dicembre 2024, abbiamo curato il design e lo sviluppo del sito web e il design dei materiali di comunicazione. Un progetto dedicato alla nuova sede delle collezioni moderne di Brera.'),
('Orientarsi nel museo','Il lavoro è proseguito con la grafica museale e il wayfinding: una segnaletica pensata per rendere il percorso espositivo più leggibile e intuitivo. Dal sito agli spazi, due interventi distinti che accompagnano l’incontro tra il pubblico e il museo.')], 'Fotografie della segnaletica installata; schermate desktop e mobile; esempi dei materiali di comunicazione; date delle fasi e crediti. Non presentare miglioramenti misurati della visita senza dati.'),
('cenacolo-vinciano','Museo del Cenacolo Vinciano','Un racconto che continua online','2019; comunicazione social documentata nel 2023','Design e sviluppo web · Video teaser · Contenuti social',['2230','2218'],[
('Preparare la visita, esplorare il capolavoro','Per il Museo del Cenacolo Vinciano abbiamo progettato e sviluppato un sito che affianca alle informazioni di accesso contenuti dedicati al museo e alle opere di Leonardo da Vinci e Donato Montorfano. Storytelling e immagini ad alta definizione arricchiscono il racconto e permettono di esplorare i dettagli del capolavoro.'),
('Dare voce al museo','Abbiamo realizzato il video teaser del sito. L’archivio documenta inoltre un successivo lavoro sui canali social, in collaborazione con il museo: contenuti che raccontano il patrimonio e invitano il pubblico a partecipare alla sua conoscenza.')], 'Schermate del sito nella versione realizzata; video teaser e crediti; esempi social; durata e perimetro delle attività. Il testo non implica una gestione social tuttora attiva.'),
('biblioteca-braidense','Biblioteca Nazionale Braidense','Collezioni e attività da scoprire online','Sito presentato nel 2023','Design web · Organizzazione dei contenuti · Calendario eventi',['2422'],[
('Una biblioteca da esplorare','Il nuovo sito della Biblioteca Nazionale Braidense presenta collezioni, fondi e attività in una struttura pensata per una consultazione chiara. Un progetto che rende visibili le diverse occasioni di scoperta offerte dalla biblioteca, dalle mostre alle attività educative.'),
('La programmazione a colpo d’occhio','Abbiamo realizzato un calendario degli eventi per consultare le attività in programma e pianificare una visita. La vita della biblioteca trova così uno spazio dedicato accanto al racconto delle sue raccolte.')], 'Schermate, calendario, dettaglio del ruolo nello sviluppo, crediti e data esatta di consegna. Usare il testo italiano specifico: il testo inglese classificato IT contiene affermazioni non verificate.'),
('poldi-pezzoli','Museo Poldi Pezzoli','Il museo, dal digitale ai materiali di visita','2023–2024','Sito web · Mappa e brochure · Identità visiva di mostra e video teaser',['2477','2493','2499'],[
('Accogliere e orientare','Per il Museo Poldi Pezzoli abbiamo realizzato una nuova mappa e una brochure: materiali pensati per accompagnare il pubblico tra le sale e offrire un primo incontro con i capolavori della collezione.'),
('Un nuovo sito per il museo','Nel 2024 l’archivio di Viva! documenta anche il nuovo sito del museo. Un intervento digitale che si affianca ai materiali di visita e apre un altro punto di accesso al racconto delle collezioni.'),
('Piero della Francesca: l’identità di una mostra','Per la mostra dedicata al Polittico agostiniano riunito abbiamo curato visual identity, design e video teaser. Un progetto distinto, da raccontare attraverso i suoi materiali e la sua identità visiva.')], 'Mappa e brochure complete; schermate del sito; visual e teaser della mostra; attribuzioni e crediti. Non estendere il lavoro a un rebranding completo del museo: il testo storico non lo dimostra.'),
('palazzo-boncompagni','Palazzo Boncompagni','Identità e comunicazione per le mostre','2023–2024','Logo e visual · Cataloghi · Advertising e social',['2440','2504'],[
('Un’identità per ogni esposizione','Per le mostre di Aldo Mondino e Mimmo Paladino a Palazzo Boncompagni abbiamo curato logo e visual, cataloghi, advertising e social. Due progetti che portano il lavoro di Viva! tra comunicazione visiva, editoria e promozione culturale.'),
('Aldo Mondino. Impertinenze a Palazzo','Nel 2023 il lavoro ha accompagnato la mostra di Aldo Mondino: dall’identità ai materiali editoriali, fino alle campagne e ai contenuti social.'),
('Mimmo Paladino nel Palazzo del Papa','Nel 2024 abbiamo lavorato alla comunicazione della mostra di Mimmo Paladino, con logo, visual, catalogo, advertising e social. Le due esposizioni offrono un’occasione per mostrare come un progetto prenda forma su supporti diversi.')], 'Copertine e interni dei cataloghi, visual, campagne e contenuti social; crediti e responsabilità. Non attribuire automaticamente a Viva! tutta la comunicazione del palazzo.'),
('galleria-cavour','Galleria Cavour 1959','Identità, arte e comunicazione','2023','Visual identity · Design · Advertising digitale · Video',['2481','2473'],[
('This is the Place','Per Galleria Cavour 1959 abbiamo curato visual identity, design e advertising digitale. Il racconto attraversa arte, moda e cultura, dando forma alla comunicazione di un luogo con molte identità e occasioni d’incontro.'),
('L’arte sulla facciata','L’archivio documenta inoltre la comunicazione digitale e il video realizzati da Viva! per l’intervento di Pietro Terzini sulla facciata della galleria. Un lavoro di racconto dell’opera e del suo incontro con lo spazio urbano.')], 'Materiali dell’identità, creatività pubblicitarie, video e fotografie dell’intervento; crediti e perimetro dei diversi incarichi. L’opera è dell’artista, non di Viva!; non aggiungere risultati commerciali non documentati.'),
('explora','Explora — Il museo dei bambini di Roma','Un sito per scoprire, giocare e imparare','2023','Progettazione · Web design · Sviluppo web',['2466'],[
('Il museo prima della visita','Per Explora, il museo dei bambini di Roma, abbiamo studiato, disegnato e sviluppato il nuovo sito web. Un progetto dedicato a un luogo in cui gioco e apprendimento si incontrano, rivolto ai bambini e agli adulti che li accompagnano.'),
('Raccontare le possibilità della scoperta','Allestimenti, attività e laboratori sono al centro del racconto del museo. Il sito presenta questo mondo di esperienze e offre un primo incontro con la sua proposta educativa.')], 'Schermate desktop e mobile, dettagli di navigazione, crediti e obiettivi. Non dichiarare conformità di accessibilità non documentata. Conservare la mappatura dello slug storico errato riferito a Milano.')]
index=['# Schede progetto — bozze complete','','Testi di lavoro per gli otto progetti selezionati. Primi quattro in ordine confermato; ordine degli altri ancora aperto. Schede non pubblicate online. Note e fonti sono solo per il lavoro interno.','','1. [Pinacoteca di Brera](brera-case-study.md)']
for n,(slug,name,tag,date,services,ids,sections,missing) in enumerate(cases,2):
 lines=[f'# {name}','','Bozza editoriale per il nuovo sito Viva! — non ancora pubblicata. Le date sono quelle dei progetti/articoli nel backup, non una dichiarazione di incarico attuale.','','## Card per la home','',f'**{name}**','',tag,'',services,'','## Apertura della scheda','',f'### {tag}','',sections[0][1],'',f'**Periodo documentato:** {date}  ',f'**Attività:** {services}','','## Racconto del progetto','']
 for title,body in sections[1:]:lines += ['### '+title,'',body,'']
 lines+=['## Chiusura','','### Un progetto da immaginare insieme?','','Parliamo di come dare forma alla tua presenza digitale e alla tua comunicazione.','','**Azione:** Parliamo del tuo progetto','','## Materiali individuati nel backup','']
 seen=set()
 for id in ids:
  p=P[id];m=M.get(p['featured_image_id'])
  if m and m['file'] and m['file'] not in seen:
   seen.add(m['file']);path=U/m['file'];assert path.is_file()
   lines += [f"- Immagine collegata a «{p['title']}»: [{m['file']}](<{path}>). File presente; selezione visiva finale da fare."]
 if not seen:lines+=['Nessuna immagine in evidenza risolta per gli articoli di riferimento. Approfondire corpo, gallerie e metadati prima di considerare il materiale assente.']
 lines+=['','## Informazioni da integrare — non pubblicare','',''+missing,'','Le metriche di risultato non sono presenti nelle fonti considerate: ometterle. Il testo può essere rifinito durante l’implementazione; i dati fattuali mancanti non vanno inventati.','','## Fonti interne','']
 for id in ids:lines += [f"- Articolo {id}: {P[id]['title']} ({P[id]['date'][:10]})."]
 file=slug+'-case-study.md';(D/file).write_text('\n'.join(lines)+'\n');index += [f'{n}. [{name}]({file})']
index+=['','## Stato','','Otto schede disponibili, inclusa Brera. Testi da rifinire insieme al layout; nessuna applicazione o pubblicazione online eseguita in questa fase. Blog e vecchi articoli restano esclusi. Terre Borromeo e Ambrosiana non fanno parte della selezione.']
(D/'case-studies.md').write_text('\n'.join(index)+'\n')
p=D/'content-direction.md';s=p.read_text();s+='\n## Schede progetto — prima stesura completata\n\nLe otto bozze sono raccolte in `case-studies.md`. L’utente ha autorizzato la preparazione di tutte le schede senza approvazione intermedia di ciascuna e successive correzioni. Primi quattro: Brera, Palazzo Citterio, Cenacolo, Braidense. Le schede sono file locali, non ancora online.\n';p.write_text(s)
print('Sette nuove schede scritte; indice degli otto progetti pronto.')
